### ISSUE TITLE
New small version checkpoint cannot load correctly

### ISSUE THREAD

**Issue by mywebinfo65536** [MzeroMiko/VMamba#92]
Hi,   I update your new code and load the classification checkpoint vssm_small_0229_ckpt_epoch_222.pth, but the error happened:

![截图20240318173400](https://github.com/MzeroMiko/VMamba/assets/105631236/528dfd62-0f60-4e4b-938f-833bbc4f2005)

Could you pls help to find the reason, thanks.

**Comment by JinxiaXie** [comment]
![微信图片_20240318213841](https://github.com/MzeroMiko/VMamba/assets/85392378/f8dc14b0-3e07-4fc7-b7e1-bd9e7f52772b)
![微信图片_20240318213900](https://github.com/MzeroMiko/VMamba/assets/85392378/e41a918a-2052-4e0b-8621-a5daddb433b8)
Can you help me? Thans a lot!

**Comment by mywebinfo65536** [comment]
> I think you may got the wrong model, as the patch embedding is 3x3 rather than 4x4 in vmamba small 0229 (while we can see in your log is 4x4).
> 
> Check the config file you use and try again.

Hi， I have checked my model： it is the latest version (vmamba.py) from the classification folder.  and indeed, the error shows the patch_embed in the **0229 pth file** is 3*3 patch_size, but the model is 4.   However,  
**(1) when I change the patch_size from 3 to 4, New errors happened:** 
![image](https://github.com/MzeroMiko/VMamba/assets/105631236/6262236a-b6c8-4b63-8e12-7584d1f23bc7)
![image](https://github.com/MzeroMiko/VMamba/assets/105631236/891a56e0-de09-4cca-8a7b-868637267933)

**(2) and then, when I change the dims from 96 to 48, New errors happened:** 
![image](https://github.com/MzeroMiko/VMamba/assets/105631236/ed9aaf09-b294-4401-a32a-3aea66093cf8)
![image](https://github.com/MzeroMiko/VMamba/assets/105631236/60e37ee0-6f9e-435e-8583-3bc8ebf60f6a)

it  seems something wrong inside?  thanks.

**Comment by MzeroMiko** [comment]
Please follow the config I provide strictly, and try again.

Or you can refer to `detection/configs/vssm1/mask_rcnn_vssm_fpn_coco_small.py`

==========================
The config of `vssm1/vssm_small_0229.yaml` writes:
```yaml
MODEL:
  TYPE: vssm
  NAME: vssm1_small_0229
  DROP_PATH_RATE: 0.3
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 15, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v3noz"
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"

# 50.4 + 8.6 + 90min/e + 36G
```
